#!/bin/bash

source config

sudo service redis stop
sudo cp ~/redis-bkp/dump.rdb /var/lib/redis/
sudo chown redis.redis /var/lib/redis/dump.rdb
sudo chmod 644 /var/lib/redis/dump.rdb
sudo service redis start
